#!/bin/sh
# =============================================================
# Date:   24.04.2025
#
# Script Name: i3-Scratchpad
# Description: Dynamic scratchpad manager for i3wm
# =============================================================

SCRATCHPAD_NAME="i3-scratch"
CFG_TERM="$HOME/.config/i3/includes/.term"
read -r MY_TERM < "$CFG_TERM"

# Check if a scratchpad terminal is running
if ! xdotool search --class "$SCRATCHPAD_NAME" > /dev/null 2>&1; then
    # Launch the terminal
    case $MY_TERM in
        "alacritty") alacritty -o window.opacity=0.93 --class "$SCRATCHPAD_NAME" & ;;
        "st") st -A 0.93 -c "$SCRATCHPAD_NAME" & ;;
        "kitty") kitty -o background_opacity=0.93 --class="$SCRATCHPAD_NAME" & ;;
        "ghostty") ghostty --background-opacity=0.93 --x11-instance-name="$SCRATCHPAD_NAME" & ;;
        *) kitty -o background_opacity=0.93 --class="$SCRATCHPAD_NAME" & ;;
    esac

    # Wait for window to appear
    while ! xdotool search --class "$SCRATCHPAD_NAME" > /dev/null 2>&1; do
        sleep 0.1
    done

    # Move it to scratchpad
    i3-msg "[class=\"$SCRATCHPAD_NAME\"] move scratchpad"
    # Show it centered
    i3-msg "[class=\"$SCRATCHPAD_NAME\"] scratchpad show"
    i3-msg "[class=\"$SCRATCHPAD_NAME\"] resize set 70 ppt 35 ppt, move position center"
else
    # Toggle it
    i3-msg "[class=\"$SCRATCHPAD_NAME\"] scratchpad show"
fi
