#!/bin/sh

THEME_CONF="$HOME/.config/i3/config_dir/theme.conf"

# Calculate average gaps since i3 only supports inner/outer, not per-side
GAP=$(( (TOP_PADDING + BOTTOM_PADDING + LEFT_PADDING + RIGHT_PADDING) / 4 ))

_write "$THEME_CONF" << EOCONF
# Generated by 01-i3.sh module

# Gaps and Borders
default_border pixel ${BORDER_WIDTH}
default_floating_border pixel ${BORDER_WIDTH}
gaps inner ${GAP}
gaps outer 0

# Colors
# class                 border          bground         text            indicator       child_border
client.focused          ${FOCUSED_BC}   ${FOCUSED_BC}   ${fg}           ${FOCUSED_BC}   ${FOCUSED_BC}
client.focused_inactive ${NORMAL_BC}    ${NORMAL_BC}    ${fg}           ${NORMAL_BC}    ${NORMAL_BC}
client.unfocused        ${NORMAL_BC}    ${NORMAL_BC}    ${fg}           ${NORMAL_BC}    ${NORMAL_BC}
client.urgent           ${red}          ${red}          ${fg}           ${red}          ${red}
client.placeholder      ${NORMAL_BC}    ${NORMAL_BC}    ${fg}           ${NORMAL_BC}    ${NORMAL_BC}
client.background       ${bg}
EOCONF

i3-msg reload
