; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini

[color]
bg = #191716
bg-alt = #708491
fg = #c5c9c5
mb = #27221e

red = #E46876
pink = #EC407A
purple = #938AA9
blue = #7FB4CA
cyan = #7AA89F
teal = #00B19F
green = #87a987
lime = #B9C244
yellow = #E6C384
amber = #FBC02D
orange = #E57C46
brown = #AC8476
grey = #8C8C8C
indigo = #6C77BB
blue-gray = #6D8895

[bar/cyn-bar]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 100%
height = 16pt

offset-x = 0pt
offset-y = 0pt

background = ${color.bg}
foreground = ${color.fg}

radius = 0pt

line-size = 2
line-color = ${color.blue}

border-size = 2pt
border-color = ${color.bg}

padding-left = 1pt
padding-right = 1pt

module-margin-left = 0pt
module-margin-right = 0pt

font-0 = "JetBrainsMono:style=Regular:size=9;2"
font-1 = "Material Design Icons Desktop:size=12;3"
font-2 = "Material Design Icons Desktop:size=13;3"
font-3 = "MesloLGS NF:style=Regular:size=14;3"

;Modules availables but not active:
;	colorpicker
modules-left = launcher sep2 browser filem terminal editor whats fetch
modules-center = bi date bd
modules-right = tray sep bi filesystem cpu_bar memory_bar bd sep bi network bd sep power

separator =
dim-value = 1.0
;locale = es_MX.UTF-8

wm-restack = i3
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[bar/cyn-bar2]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = true
fixed-center = true

width = 100%
height = 16pt

offset-x = 0pt
offset-y = 0pt

background = ${color.bg}
foreground = ${color.fg}

radius = 0pt

line-size = 2
line-color = ${color.blue}

border-size = 2pt
border-color = ${color.bg}

padding-left = 1pt
padding-right = 1pt

module-margin-left = 0pt
module-margin-right = 0pt

font-0 = "JetBrainsMono:style=Regular:size=9;2"
font-1 = "Material Design Icons Desktop:size=12;3"
font-2 = "Material Design Icons Desktop:size=13;3"
font-3 = "MesloLGS NF:style=Regular:size=14;3"
font-4 = "Font Awesome 6 Free Solid:size=9;2"

;Modules availables but not active:
;	xkeyboard
modules-left = bi i3 bd sep title
modules-center = 
modules-right = bluetooth sep brightness sep usercard sep battery sep weather sep bi pulseaudio bd sep updates sep mpd_control sep mpd

separator =
dim-value = 1.0
;locale = es_MX.UTF-8

wm-restack = i3
enable-ipc = true

cursor-click = pointer
cursor-scroll = ns-resize

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = true
